version: '3.8'

services:
  web:
    build: .
    command: python /application/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/application
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres  # Change this in a real setup
      - POSTGRES_DB=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: jbur645@wgu.edu  # Change this as needed
      PGADMIN_DEFAULT_PASSWORD: joelburns  # Change this as needed
    ports:
      - 5050:80
    depends_on:
      - db

volumes:
  postgres_data: